const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.SVGPicture,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Persist,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.UserMedia,
		C3.Plugins.video,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.LOS.Exps.HitX,
		C3.Behaviors.LOS.Exps.HitY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.ScheduleNextPlay
	];
};
self.C3_JsPropNameTable = [
	{fundo2: 0},
	{Plataforma: 0},
	{galinha: 0},
	{Sólido: 0},
	{Parede: 0},
	{chão_fase_2: 0},
	{ImagemSVG: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Mosaico: 0},
	{chao1: 0},
	{Persistir: 0},
	{heart1: 0},
	{barreira: 0},
	{Senóide: 0},
	{Sprite6: 0},
	{Teclado: 0},
	{aparadorLaser: 0},
	{fundoStart1: 0},
	{fonte_de_sprites: 0},
	{titulo: 0},
	{active: 0},
	{tempoDefault: 0},
	{tempoOff: 0},
	{tempoOn: 0},
	{CampoDeVisão: 0},
	{laserBase: 0},
	{laserLight: 0},
	{PLAY: 0},
	{Mouse: 0},
	{espinhos: 0},
	{espinhos_caixa: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{barraVida: 0},
	{Mosaico2: 0},
	{Teto: 0},
	{Teleport: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Teleport2: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Plano_fundo_fase3: 0},
	{Mosaico3: 0},
	{PularAtravés: 0},
	{chão_fase_3: 0},
	{Sprite: 0},
	{chão_atr_fase_3: 0},
	{Cronômetro: 0},
	{chão_some_fase_3: 0},
	{Sine: 0},
	{alien: 0},
	{arma: 0},
	{galinhaArma: 0},
	{audio: 0},
	{MídiaDoUsuário: 0},
	{Vídeo: 0},
	{plataformaQuebra: 0},
	{plataformaQuebra2: 0},
	{plataformaQuebra3: 0},
	{BOSS: 0},
	{Fundo_gameover: 0},
	{GAME_OVER: 0},
	{Agradecimento: 0},
	{Projétil: 0},
	{bala: 0},
	{YOUWIN: 0},
	{barraBoss: 0},
	{Teleport3: 0},
	{Nomes: 0},
	{ENTER: 0},
	{boom: 0},
	{bala2: 0},
	{Vidas: 0},
	{vidaBoss: 0}
];

self.InstanceType = {
	fundo2: class extends self.ISpriteInstance {},
	galinha: class extends self.ISpriteInstance {},
	Parede: class extends self.ISpriteInstance {},
	chão_fase_2: class extends self.ISpriteInstance {},
	ImagemSVG: class extends self.ISVGPictureInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	chao1: class extends self.ISpriteInstance {},
	heart1: class extends self.ISpriteInstance {},
	barreira: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	aparadorLaser: class extends self.ISpriteInstance {},
	fundoStart1: class extends self.ISpriteInstance {},
	fonte_de_sprites: class extends self.ISpriteFontInstance {},
	titulo: class extends self.ISpriteInstance {},
	laserBase: class extends self.ISpriteInstance {},
	laserLight: class extends self.ISpriteInstance {},
	PLAY: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	espinhos: class extends self.ISpriteInstance {},
	espinhos_caixa: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	barraVida: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Teto: class extends self.ISpriteInstance {},
	Teleport: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Teleport2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Plano_fundo_fase3: class extends self.ISpriteInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	chão_fase_3: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	chão_atr_fase_3: class extends self.ISpriteInstance {},
	chão_some_fase_3: class extends self.ISpriteInstance {},
	alien: class extends self.ISpriteInstance {},
	arma: class extends self.ISpriteInstance {},
	galinhaArma: class extends self.ISpriteInstance {},
	audio: class extends self.IInstance {},
	MídiaDoUsuário: class extends self.IWorldInstance {},
	Vídeo: class extends self.IWorldInstance {},
	plataformaQuebra: class extends self.ISpriteInstance {},
	plataformaQuebra2: class extends self.ISpriteInstance {},
	plataformaQuebra3: class extends self.ISpriteInstance {},
	BOSS: class extends self.ISpriteInstance {},
	Fundo_gameover: class extends self.ISpriteInstance {},
	GAME_OVER: class extends self.ISpriteInstance {},
	Agradecimento: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	YOUWIN: class extends self.ISpriteInstance {},
	barraBoss: class extends self.ISpriteInstance {},
	Teleport3: class extends self.ISpriteInstance {},
	Nomes: class extends self.ITextInstance {},
	ENTER: class extends self.ISpriteInstance {},
	boom: class extends self.ISpriteInstance {},
	bala2: class extends self.ISpriteInstance {}
}